version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=hajj_employment
      - DB_USERNAME=hajj_user
      - DB_PASSWORD=secret
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql
      - redis
    networks:
      - hajj-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hajj_employment
      MYSQL_USER: hajj_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hajj-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hajj-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: hajj_user
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - hajj-network

volumes:
  mysql_data:

networks:
  hajj-network:
    driver: bridge 